name: Generate Wordle Data
on:
  # Schedule daily updates
  schedule: [{cron: "*/30 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run deno grab action
        run: deno task grab
      # auto-commit suggestions
      - uses: stefanzweifel/git-auto-commit-action@v4
